### ISSUE TITLE
Users that own own coin, and use verify - have to buy own coin again

### ISSUE THREAD

**Issue by tijno** [deso-protocol/backend#101]
See post here:
https://bitclout.com/posts/d1d744e312bada41f2c1cd2aec7f81a56cc7be2342908d4fed3fe762c70771d7

Steps:
1. User owns own coin
2. User uses Jumio verify
3. User tries to transfer coins

Gets error to buy coin again.

Triggered by this line i think:

https://github.com/bitclout/backend/blob/be466b5a1b73848b02e447a314f6f452c0bfaedc/routes/transaction.go#L126

And reason is `MustPurchaseCreatorCoin` is set to true, 

https://github.com/bitclout/backend/blob/be466b5a1b73848b02e447a314f6f452c0bfaedc/routes/verify.go#L776

But `HasPurchasedCreatorCoin` is not set to true during verification for users that have already purchased their own coin.

Its only set when they do it again:

https://github.com/bitclout/backend/blob/be466b5a1b73848b02e447a314f6f452c0bfaedc/routes/transaction.go#L109

**Comment by theparkerazzi** [comment]
So all the accounts I have made I actually use...Am I able to verify multiple accounts? It seems like....nm
