### ISSUE TITLE
backend can not start with default ulimit

### ISSUE THREAD

**Issue by electro89** [deso-protocol/backend#164]
The back end did not start next day after closing. Error was too much open file message. Default ulimit was 1024, Only when I typed this cmd 
`ulimit -n 10000`
back end could start. I think this should be in documentation if someone encounter such scenario.

OS: Xubuntu
Hard disk : Normal hard disk( not SSD )

**Comment by maebeam** [comment]
Yes, this should be documented. Thanks for raising this issue. If you'd like to open a PR and add it to the README under "Common Issues" that would be great

**Comment by electro89** [comment]
Thanks for the quick reply. I hope you could add it after checking it more with hardware limitations such as this.
