### ISSUE TITLE
buy DeSo with 1.8 ETH, but DeSo not transfer to my account

### ISSUE THREAD

**Issue by deso2021** [deso-protocol/backend#197]
hello, I am https://bitclout.com/u/sixbit . Buy some Deso from bitclout.com with eth, but I don't get the deso.
I have mail to admin(node.admin@bitclout.com), but still in process, maybe core devs has too many mail, not notice my case, can anyone help me, thank you very much.

1.  my eth address is 0x739477a2305f5502406580091ff0a5db292e5b40,  the transaction is https://etherscan.io/tx/0x691ef256ef04d1b0d97655581796b72df319cd8f16eac0c02622693ec9a59add , 1.8 eth has send to platform address
- My public key: BC1YLhaLKVZUxVJdhPbfcg1skMf5xjHWsqMZWPdGeRj5Fh4wS2vKW4K 
- [My Wallet](https://www.bitcloutpulse.com/app/wallet/BC1YLhaLKVZUxVJdhPbfcg1skMf5xjHWsqMZWPdGeRj5Fh4wS2vKW4K)
- My BTC Address: 1GFxEQyEvLLBky1ZKUnM4zKnG47unj11Lu

2. this is my account, no coin send to me
![image](https://user-images.githubusercontent.com/93238790/139614407-c262b556-4a07-4ac3-a6fc-5815b89d8e73.png)

3. I found another 2 user have same problem, they said it  occur recently.does relate to this commit ? https://github.com/deso-protocol/backend/commit/bffadcb314a9eeb35752df5283605101377f8e8a
- when I submit swap eth to deso, about an hour. I found there are two transaction from my address to platform address, the amount are not same, but both ~ 1.8eth.  first one is finished, second is pending. maybe a bug lead to submit twice?
-  ~7 hour later，the pending transaction dropped. https://etherscan.io/tx/0xb1bbba7266cbc4d46f6e18b20cdc7bdf6e49bc5988621c111afd7eb30de50ca7

**Comment by maebeam** [comment]
node.admin@bitclout.com will respond shortly

**Comment by deso2021** [comment]
thanks you, got it !
![image](https://user-images.githubusercontent.com/93238790/139757247-5e51ecbb-16c7-4e2d-abe2-044b25902c7e.png)
