### ISSUE TITLE
Using NodeSource triggers RuleErrorTxnFeeBelowNetworkMinimum error

### ISSUE THREAD

**Issue by tijno** [deso-protocol/backend#279]
Running latest backend image. Tested #275 with `NODE_SOURCE=6` in dev.env but this causes issue with diamonding:

> E0119 12:02:44.144302       1 shared.go:30] SubmitTransaction: Problem processing transaction: VerifyAndBroadcastTransaction: Problem validating txn: ValidateTransaction: Problem validating transaction: : RuleErrorTxnFeeBelowNetworkMinimum

Not tested other transactions.

cc @superzordon

**Comment by superzordon** [comment]
Interesting, haven't seen that before in my dev env. Do you experience this only when the `node-source` flag is set?

**Comment by lazynina** [comment]
We need to add the extra data before we construct the transaction

**Comment by lazynina** [comment]
Or increase your min fee rate nanos per kb a little until it is fixed
