### ISSUE TITLE
GetNotifications Error After Clean Sync and Fresh Images

### ISSUE THREAD

**Issue by AdonousTech** [deso-protocol/backend#282]
I decided to do a clean sync and pull after the DAO updates because I was seeing some weird data type mismatches. After the clean sync and pulling in the latest images, I encounter this error when trying to fetch notifications via the OOB frontend app:

`E0120 19:11:40.562831       1 shared.go:30] GetNotifications: Problem encoding response as JSON: json: unsupported type: map[lib.PKID]lib.CoinEntry|` 

The error is triggered here during GetAppState:

https://github.com/deso-protocol/backend/blob/3caad5db8851896ab95a0928ae094e63263181c5/routes/base.go#L425

Any ideas what's causing this?

**Comment by tijno** [comment]
Looks like your using stable backe nd 2.0.1 repease. The issue was present there but was fixed in  backend:latest.

**Comment by AdonousTech** [comment]
Ahh, OK. Let me try that. I'll close this one out! Thanks!
