### ISSUE TITLE
get-posts-stateless with MediaRequired = true does not work correctly.

### ISSUE THREAD

**Issue by pangia** [deso-protocol/backend#288]
The get-posts-stateless call does not limit the results to media only content when the MediaRequired bool is set to true.

**Comment by chafreaky** [comment]
Can you provide an example call?

**Comment by pangia** [comment]
Just call get-posts-stateless with 
"NumToFetch" = 100 & "MediaRequired" = true


results will include posts with:
 "ImageURLs": null,
 "VideoURLs": null,

**Comment by chafreaky** [comment]
Have you checked PostExtraData? The flag also includes posts with embedded
content which won’t show in those keys

**Comment by pangia** [comment]
Update: 

It looks like the post.go code does not consider the MediaRequired flag when it is not pulling for global or follower feed.

**Comment by lazynina** [comment]
This will be resolved with #309
