### ISSUE TITLE
/api/v1/block from current docker image returns undecoded values for ExtraData

### ISSUE THREAD

**Issue by starykolarz** [deso-protocol/backend#291]
I just upgraded to current version of docker. In the new version, /api/v1/block started returning ExtraData for transactions - but returns undecoded data; below example transaction from block 101624. It's the same case for all ExtraData fields in this block, regardeless of transaction type.

 {
         "TransactionIDBase58Check": "3JuETVZYaW7QqfAX5qGyP9ovDTGS8gTT5VQexqorBkBxpVh9Bfj7jY",
         "RawTransactionHex": "025d38f2fcbe9389c9b1f873c0c34fb1cf60558da1e3d4a33b8325e1db1eac034400d1412411f074d03a356637473d1f317ca3927f92dbd156f490312fb1ae9cbc08000203ab58c3dc9fb759f4c360defc46b37aecdebfa97e2576a6d91eb7d0a6e9bf1e88d086030376af0ba7c9b7d39952c1871fbdd0aafb293c7dabaa7434d5fd6bde871e6fdfa58e84010200210376af0ba7c9b7d39952c1871fbdd0aafb293c7dabaa7434d5fd6bde871e6fdfa50310446572697665645075626c69634b657921022ae6ab19cccb8e7602a6bd9c99e70b0e3d7474173f93ae610300c76baf9a44f30c4469616d6f6e644c6576656c01020f4469616d6f6e64506f73744861736820bb9af04b873c4536454fdb9b777d707dbef9319a1161e0e9b6d19725da5d8532473045022100bbdbed665c50deeb9ed370fa7b40e868f042094650a3eea0a318211eea131304022015d678716f697a730f97f08804c56e424372b56e44bda85e835de0bc10bb645b",
         "Inputs":          [
                        {
               "TransactionIDBase58Check": "3JuETSpxnR1nV71vXE1cVmYF5RPWxu2uvk7VFYkVWX56En2tkm6gi7",
               "Index": 0
            },
                        {
               "TransactionIDBase58Check": "3JuEUKvqvPgCjF5h7pN1BZe8B3AUiUvvDRgzKe9i32iRV7yhWf4td5",
               "Index": 0
            }
         ],
         "Outputs":          [
                        {
               "PublicKeyBase58Check": "BC1YLiv5UFukvSH4VuBNjkQr8bXeHFVCUQY5StvSSvuZtajoQHmsnVb",
               "AmountNanos": 50000
            },
                        {
               "PublicKeyBase58Check": "BC1YLiWtGNvd93vgHqtcZMSW7XSt7KrZx33dim3ibm6NgoshedscNJK",
               "AmountNanos": 16910
            }
         ],
         "SignatureHex": "3045022100bbdbed665c50deeb9ed370fa7b40e868f042094650a3eea0a318211eea131304022015d678716f697a730f97f08804c56e424372b56e44bda85e835de0bc10bb645b",
         "TransactionType": "BASIC_TRANSFER",
         "BlockHashHex": "000000000000637e3edcb17f5013532e8fd6f66ae4a57d6ed8d05fe9cd406d6e",
         "TransactionMetadata":          {
            "BlockHashHex": "000000000000637e3edcb17f5013532e8fd6f66ae4a57d6ed8d05fe9cd406d6e",
            "TxnIndexInBlock": 904,
            "TxnType": "BASIC_TRANSFER",
            "TransactorPublicKeyBase58Check": "BC1YLiWtGNvd93vgHqtcZMSW7XSt7KrZx33dim3ibm6NgoshedscNJK",
            "AffectedPublicKeys":             [
                              {
                  "PublicKeyBase58Check": "BC1YLiv5UFukvSH4VuBNjkQr8bXeHFVCUQY5StvSSvuZtajoQHmsnVb",
                  "Metadata": "BasicTransferOutput"
               },
                              {
                  "PublicKeyBase58Check": "BC1YLiWtGNvd93vgHqtcZMSW7XSt7KrZx33dim3ibm6NgoshedscNJK",
                  "Metadata": "BasicTransferOutput"
               }
            ],
            "TxnOutputs":             [
                              {
                  "PublicKey": "A6tYw9yft1n0w2De/Eazeuzev6l+JXam2R630Kbpvx6I",
                  "AmountNanos": 50000
               },
                              {
                  "PublicKey": "A3avC6fJt9OZUsGHH73QqvspPH2rqnQ01f1r3oceb9+l",
                  "AmountNanos": 16910
               }
            ],
            "BasicTransferTxindexMetadata":             {
               "TotalInputNanos": 70120,
               "TotalOutputNanos": 66910,
               "FeeNanos": 3210,
               "UtxoOpsDump": "",
               "UtxoOps": null,
               "DiamondLevel": 1,
               "PostHashHex": "bb9af04b873c4536454fdb9b777d707dbef9319a1161e0e9b6d19725da5d8532"
            }
         },
         "ExtraData":          {
            "DerivedPublicKey": "\u0002*��\u0019�ËŽv\u0002�����\u000b\u000e=tt\u0017?��a\u0003\u0000�k��D�",
            "DiamondLevel": "\u0002",
            "DiamondPostHash": "���K�<E6EOŰ›w}p}��1�\u0011a���Ń—%�]�2"
         }
      }

**Comment by tholonious** [comment]
Working on a fix here: https://github.com/deso-protocol/backend/pull/306

**Comment by lazynina** [comment]
@starykolarz - this has been resolved with this PR in core: https://github.com/deso-protocol/core/pull/222

Additional details on the issue can be found in my response [here](https://github.com/deso-protocol/core/issues/227#issuecomment-1050240047)

We are currently resyncing txindex and blocks 106179 and 106180 will have all the transaction metadata in txindex
