### ISSUE TITLE
update-profile wrong doc ref

### ISSUE THREAD

**Issue by afaraha8403** [deso-protocol/backend#301]
Under this line it states `UpdaterPublicKeyBase58Check` https://github.com/deso-protocol/backend/blob/709cbfbc62cf3a0e6d56c393e555fc277c93fb76/routes/transaction.go#L272

The docs below state `UpdatePublicKeyBase58Chck`
https://docs.deso.org/for-developers/backend/transactions/construct-transactions/social-transactions-api#update-profile

Seems to be a spelling mistake in the docs

**Comment by lazynina** [comment]
thanks @afaraha8403 - this has been fixed here: https://github.com/deso-protocol/docs/commit/d7da459ae1b37848ee89edb7c40f5fd0e333c9f5

In the future, please open issues related to docs in the docs repo [here](https://github.com/deso-protocol/docs)
