### ISSUE TITLE
ExtraData in ProfileEntryResponse is always null

### ISSUE THREAD

**Issue by merohitnishad** [deso-protocol/backend#342]
I'm trying to update profile to "/api/v0/update-profile" with ExtraData in request payload.

 const request = this.post(endpoint, BackendRoutes.RoutePathUpdateProfile, {
      UpdaterPublicKeyBase58Check,
      ProfilePublicKeyBase58Check,
      NewUsername,
      NewDescription,
      NewProfilePic,
      NewCreatorBasisPoints,
      NewStakeMultipleBasisPoints,
      IsHidden,
      MinFeeRateNanosPerKB,
      ExtraData
    }).....
where ExtraData is a JSON Object 
Eg :  
{
nickname: rohit
}
I got response from server and also I've signed the transaction and submitted it. Even I'm getting 
{
  "TxnFound": true
}
from "api/v0/get-txn" .

But after this when I'm trying to get profile details from "/api/v0/get-single-profile" , the ExtraData is still null .

**Comment by tijno** [comment]
Are you doing this on mainnet or testnet?

Mainnet fork for extra data on profile has not triggered yet (actually still needs to be scheduled)

https://github.com/deso-protocol/core/blob/main/lib/constants.go#L651

**Comment by merohitnishad** [comment]
I am doing it on mainnet, tried on api of node.deso.org and api.tijn.club

**Comment by tijno** [comment]
Yeah so that wont do anything as it requires hardfork first. You can try on test.deso.org which is running testnet - but you need to ask the team for some test deso.

**Comment by merohitnishad** [comment]
Changing constants value in https://github.com/deso-protocol/core/blob/main/lib/constants.go made the way. Now I can get the data.
