### ISSUE TITLE
/api/v1/transaction-info error on node.deso.org -> "Error": "APITransactionInfo: This function cannot be called without passing --txindex to the node on startup."

### ISSUE THREAD

**Issue by starykolarz** [deso-protocol/backend#343]
Looks like a configuration error?

Input/output below.

https://node.deso.org/api/v1/transaction-info

input:
2022-05-07 10:43:15.709 +02:00 [VRB] {
  "TransactionIDBase58Check": "",
  "PublicKeyBase58Check": "BC1YLhhyc93qkPusbYMXxfJaWGjEPrRgDvYAASha8WgyJtu77uYD8Rw",
  "Limit": 1000,
  "LastPublicKeyTransactionIndex": 0,
  "IsMempool": false,
  "IDsOnly": true
} {  }

output:
2022-05-07 10:43:15.857 +02:00 [VRB] Response as json:
 {
  "Error": "APITransactionInfo: This function cannot be called without passing --txindex to the node on startup."
} {  }

**Comment by starykolarz** [comment]
Exact same call (same input) on bitlclout.com works and returns: 

{
   "Error": "",
   "Transactions":    [
      {"TransactionIDBase58Check": "3JuESvfusoYDot4jcLHLH2xy5VSpbX1wZ5uXQXVgbNMCfkaJ5NdZoN"},
      {"TransactionIDBase58Check": "3JuESneNnssXqH5hUVw1fpBJgRzZqBXGAenGTpPCe8B2yt4tvLfp4w"},
      {"TransactionIDBase58Check": "3JuETZovzcQchsaFHGa4QaEBuRvpoHvBD65hxWq1na9MuBvxbZKhMw"},
      {"TransactionIDBase58Check": "3JuEU19V2qjw4WcPA7fezZCv2wV6htxszyLuTuXsntU24eokeL625V"}
   ],
   "LastTransactionIDBase58Check": "",
   "LastPublicKeyTransactionIndex": 0,
   "BalanceNanos": 9144
}

**Comment by tijno** [comment]
yeah looks like both txindex and supply-stats have been disabled on node.deso.org

@lazynina is this permanent change or temp due to yesterdays google issues?

**Comment by lazynina** [comment]
@tijno I believe this was a temporary change to the flags passed to node.deso.org

**Comment by diamondhands0** [comment]
Hey all, txindex should be back this weekend. See my reply here:

https://diamondapp.com/posts/498fe74e4741aa94b59f0c902f6ae0a1012f33dbb20518647c9f61c68a31c799?feedTab=Hot&tab=posts

**Comment by starykolarz** [comment]
Working now - closing.
Thank you!
