### ISSUE TITLE
New Derived Key Issue with Fork

### ISSUE THREAD

**Issue by sungkhum** [deso-protocol/backend#455]
Getting this error on code that used to work

```
'error': 'SubmitTransaction: Problem processing transaction: VerifyAndBroadcastTransaction: Problem validating txn: ValidateTransaction: Problem validating transaction: : ConnectTransaction: : _connectAuthorizeDerivedKey: It looks like this transaction was signed with a derived key, but the signature is malformed: : IsDerivedSignature: signature has high s: RuleErrorTxnSigHasHighS'} | Authorize Derived Key: {'error': 'SubmitTransaction: Problem processing transaction: VerifyAndBroadcastTransaction: Problem validating txn: ValidateTransaction: Problem validating transaction: : ConnectTransaction: : _connectAuthorizeDerivedKey: It looks like this transaction was signed with a derived key, but the signature is malformed: : IsDerivedSignature: signature has high s: RuleErrorTxnSigHasHighS'}
-- | --
```

@lazynina Do I need to change something in my code? Or was a bug introduced that needs to be fixed on DeSo's end?

**Comment by lazynina** [comment]
@sungkhum - DeSo now required that all signatures have a low-s value for security purposes. Can you share the code you're using to sign transactions? I can likely help you resolve the issue.

If using code similar to how identity signs transactions, you'll need to use the option canonical: true when signing transactions to ensure a low s signature is produced. So something like the code below.

```
  const signature = privateKey.sign(transactionHash, { canonical: true });
```

For more info on ECDSA signature malleability, you can see this link: https://coders-errand.com/malleability-ecdsa-signatures/

**Comment by sungkhum** [comment]
@lazynina This broke a lot of apps today (including mine). Would be great to get a heads up on these in the Dev channel without us having to comb through the fork code ourselves.

I fixed it in the Python code I was using by adding:
```
if s > n // 2:
        s = n - s
```
https://github.com/ItsAditya-xyz/DeSo.py/pull/35/commits/94db845e7138e305684bd999285414e567c96c13

Thanks for the response!

**Comment by sungkhum** [comment]
Tested a few times and it worked, but honestly not sure if I fixed it.

**Comment by lazynina** [comment]
@sungkhum - apologies, I thought I included it in the release notes more clearly but it was only in the auto-generated notes section of the release.
