### ISSUE TITLE
backend erro

### ISSUE THREAD

**Issue by osontungo** [deso-protocol/backend#494]
![Screenshot from 2023-05-19 22-49-04](https://github.com/deso-protocol/backend/assets/115781152/a8b8fdcf-eda6-49d4-bcea-357f85d7411b)

**Comment by osontungo** [comment]
[+] Building 4.2s (26/29)                                                       
 => [internal] load build definition from Dockerfile                       0.1s
 => => transferring dockerfile: 964B                                       0.0s
 => [internal] load .dockerignore                                          0.1s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/library/alpine:latest           3.7s
 => [stage-1 1/3] FROM docker.io/library/alpine:latest@sha256:02bb6f42843  0.2s
 => => resolve docker.io/library/alpine:latest@sha256:02bb6f428431fbc2809  0.1s
 => => sha256:02bb6f428431fbc2809c5d1b41eab5a68350194fb50 1.64kB / 1.64kB  0.0s
 => => sha256:c0669ef34cdc14332c0f1ab0c2c01acb91d96014b172f1a 528B / 528B  0.0s
 => => sha256:5e2b554c1c45d22c9d1aa836828828e320a26011b76 1.47kB / 1.47kB  0.0s
 => [internal] load build context                                          0.1s
 => => transferring context: 2B                                            0.0s
 => CACHED [backend  2/23] RUN apk update                                  0.0s
 => CACHED [backend  3/23] RUN apk upgrade                                 0.0s
 => CACHED [backend  4/23] RUN apk add --update go gcc g++ vips-dev        0.0s
 => CACHED [backend  5/23] WORKDIR /deso/src                               0.0s
 => ERROR [backend  6/23] COPY backend/go.mod backend/                     0.0s
 => ERROR [backend  7/23] COPY backend/go.sum backend/                     0.0s
 => ERROR [backend  8/23] COPY core/go.mod core/                           0.0s
 => ERROR [backend  9/23] COPY core/go.sum core/                           0.0s
 => CACHED [backend 10/23] WORKDIR /deso/src/backend                       0.0s
 => CACHED [backend 11/23] RUN go mod download                             0.0s
 => ERROR [backend 12/23] COPY backend/apis      apis                      0.0s
 => ERROR [backend 13/23] COPY backend/config    config                    0.0s
 => ERROR [backend 14/23] COPY backend/cmd       cmd                       0.0s
 => ERROR [backend 15/23] COPY backend/miner     miner                     0.0s
 => ERROR [backend 16/23] COPY backend/routes    routes                    0.0s
 => ERROR [backend 17/23] COPY backend/countries countries                 0.0s
 => ERROR [backend 18/23] COPY backend/main.go   .                         0.0s
 => ERROR [backend 19/23] COPY core/desohash ../core/desohash              0.0s
 => ERROR [backend 20/23] COPY core/cmd       ../core/cmd                  0.0s
 => ERROR [backend 21/23] COPY core/lib       ../core/lib                  0.0s
 => ERROR [backend 22/23] COPY core/migrate   ../core/migrate              0.0s
------
 > [backend  6/23] COPY backend/go.mod backend/:
------
------
 > [backend  7/23] COPY backend/go.sum backend/:
------
------
 > [backend  8/23] COPY core/go.mod core/:
------
------
 > [backend  9/23] COPY core/go.sum core/:
------
------
 > [backend 12/23] COPY backend/apis      apis:
------
------
 > [backend 13/23] COPY backend/config    config:
------
------
 > [backend 14/23] COPY backend/cmd       cmd:
------
------
 > [backend 15/23] COPY backend/miner     miner:
------
------
 > [backend 16/23] COPY backend/routes    routes:
------
------
 > [backend 17/23] COPY backend/countries countries:
------
------
 > [backend 18/23] COPY backend/main.go   .:
------
------
 > [backend 19/23] COPY core/desohash ../core/desohash:
------
------
 > [backend 20/23] COPY core/cmd       ../core/cmd:
------
------
 > [backend 21/23] COPY core/lib       ../core/lib:
------
------
 > [backend 22/23] COPY core/migrate   ../core/migrate:
------
Dockerfile:31
--------------------
  29 |     COPY core/cmd       ../core/cmd
  30 |     COPY core/lib       ../core/lib
  31 | >>> COPY core/migrate   ../core/migrate
  32 |     
  33 |     # build backend
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref moby::tczxsuowj3d1ysgbbkv6asibh: failed to walk /var/lib/docker/tmp/buildkit-mount1264646861/core: lstat /var/lib/docker/tmp/buildkit-mount1264646861/core: no such file or directory

**Comment by lazynina** [comment]
@osontungo - you need to pull down the [core repo](https://github.com/deso-protocol/core) into a sibling directory along your backend repo.
